### PR TITLE
Feature: Hide Players around shared & guessed hoppity eggs

### PR DESCRIPTION
**Pull request by RobotHanzo**
## What
Hides players within a proximity of 4 blocks within a shared or guessed egg waypoint

<details>
<summary>Images</summary>

Before
image
After
image

</details>

## Changelog New Features
+ Hide Players around shared & guessed hoppity eggs - RobotHanzo

### CODE REVIEW

**Comment by hannibal002** [comment]
You cant click thought the players, still. and without seeing the players you dont know how to position yourself so you can click the egg without having players in front of you.

**Comment by RobotHanzo** [comment]
> You cant click thought the players, still. and without seeing the players you dont know how to position yourself so you can click the egg without having players in front of you.

I'm working on a PR to redirect clicks from the players to the egg itself rn

**Comment by ThatGravyBoat** [comment]
It would be better if this lowered the opacity of the players instead.

**Comment by ThatGravyBoat** [comment]
> > You cant click thought the players, still. and without seeing the players you dont know how to position yourself so you can click the egg without having players in front of you.
> 
> 
> 
> I'm working on a PR to redirect clicks from the players to the egg itself rn

That sounds very much like a cheat?

**Comment by CalMWolfs** [comment]
> That sounds very much like a cheat?

Yeah this is something we cant have in skyhanni

**Pull request closed without merging**
