### PR TITLE
Backend: Cleanup HoppityCollectionStats to improve readability

### PR DESCRIPTION
**Pull request by walkerselby**
## What
Cleanup HoppityCollectionStats to improve readability.

## Changelog Technical Details
+ Cleanup HoppityCollectionStats to improve readability. - walker

### CODE REVIEW

**Comment by CalMWolfs** [comment]
Will look at this after the other two prs that also touch this file

**Comment by hannibal002** [comment]
> Will look at this after the other two prs that also touch this file

should we make this pr depend on the other prs?

**Comment by CalMWolfs** [comment]
> > Will look at this after the other two prs that also touch this file
> 
> should we make this pr depend on the other prs?

I think we can leave it like this as chocolate factory starts in like 20 hours so this shouldnt be open for too long

**Review by hannibal002 — CHANGES_REQUESTED** [review]
merge conflict

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
