### PR TITLE
Backend: Add event inheritance

### PR DESCRIPTION
**Pull request by ThatGravyBoat**
## What
Adds back event class inheritance as previously not included in #2008 
This will create an event handler on the first post of an event and will include all listeners from all super classes.

The changes can be viewed in this commit https://github.com/hannibal002/SkyHanni/commit/c41bc1bf5db7bbc26786ae5eb1b1183c6e85717f
This PR also contains moving `WorldClickEvent` to `SkyHanniEvent` to demonstrate this.

## Changelog Technical Details
+ Added SkyHanni event inheritance. - ThatGravyBoat

### CODE REVIEW

**Comment by hannibal002** [comment]
@nea89o would love to see your feedback on this

**Comment by btwonion** [comment]
should this pr also port all existing events to SkyHanniEvent or should this pr only implement the concept?

**Comment by hannibal002** [comment]
The bigger the pr, the harder to test and review.
I think we can move old prs over to the new system slowly and later, first we need the new system working

**Comment by CalMWolfs** [comment]
> should this pr also port all existing events to SkyHanniEvent or should this pr only implement the concept?

This would be a change of ~3000 additons & 3000 deletions

**Comment by btwonion** [comment]
I see. The system works for me as of now. Is it only the reviewing holding on the pr or are there still things to be implemented?

**Comment by ThatGravyBoat** [comment]
Please Hanni merge 🥺

**Review by CalMWolfs — APPROVED** [review]
worked for me in my testing

**Pull request merged**
