### PR TITLE
Backend: Add feature toggle adapter to automatically turn on features

### PR DESCRIPTION
**Pull request by lineargraph**
## Changelog Technical Details
+ Added feature toggle adapter to automatically turn on features. - nea

### CODE REVIEW

**Comment by hannibal002** [comment]
Where is the check so that this only happened when using a beta, not a full version?

**Comment by lineargraph** [comment]
> Where is the check so that this only happened when using a beta, not a full version?

There is none. You can just only add that adapter if you are in a beta.

GsonBuilder()
.also {
	if(isInBeta())
	it.registerTypeAdapterFactory(FeatureAdapterThingyIWrote)
}

I'm not sure if there is a way to detect betas yet?

**Comment by hannibal002** [comment]
> I'm not sure if there is a way to detect betas yet?

not yet. would just hook into the auto updater class for this

**Review by hannibal002 — CHANGES_REQUESTED** [review]
Does not set all features to enabled when starting without a config.

**Comment by hannibal002** [comment]
```
java.lang.NoSuchFieldException: highlighters
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at at.hannibal2.skyhanni.utils.FeatureTogglesByDefaultAdapter$Adapter.read(FeatureTogglesByDefaultAdapter.kt:53)
	at at.hannibal2.skyhanni.utils.FeatureTogglesByDefaultAdapter$Adapter.read(FeatureTogglesByDefaultAdapter.kt:56)
	at at.hannibal2.skyhanni.utils.FeatureTogglesByDefaultAdapter$Adapter.read(FeatureTogglesByDefaultAdapter.kt:56)
	at com.google.gson.Gson.fromJson(Gson.java:803)
	at com.google.gson.Gson.fromJson(Gson.java:868)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at at.hannibal2.skyhanni.config.ConfigManager$firstLoadFile$run$1.invoke(ConfigManager.kt:207)
	at at.hannibal2.skyhanni.config.ConfigManager.firstLoadFile(ConfigManager.kt:210)
	at at.hannibal2.skyhanni.config.ConfigManager.firstLoad(ConfigManager.kt:174)
	at at.hannibal2.skyhanni.SkyHanniMod.init(SkyHanniMod.kt:720)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:495)
	at net.minecraft.client.Minecraft.run(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
```

**Comment by hannibal002** [comment]
will move this back in priority once again (im totally going to merge this one day, trust)

**Review by hannibal002 — APPROVED** [review]
image

**Pull request merged**
