### PR TITLE
Disabled effect highlight

### PR DESCRIPTION
**Pull request by superhize**
idk i though about that while doing bingo

### CODE REVIEW

**Comment by jani270** [comment]
This is a dupe of Skytils Highlight Disabled Potion Effects feature, not sure if you wanna go this way
image

**Comment by superhize** [comment]
> This is a dupe of Skytils Highlight Disabled Potion Effects feature, not sure if you wanna go this way image

Hannibal told me in pm, didn't know it was already a thing

It's still open cause he said we still can add it to sh, you choose what you want to do

**Comment by hannibal002** [comment]
@jani270 you choose

**Comment by hannibal002** [comment]
jani chose not to use this. If Skytils dies in 1.20 and SkyHanni is updated, we can read this again.

**Pull request closed without merging**
