### PR TITLE
Backend: Dekekt

### PR DESCRIPTION
**Pull request by DavidArthurCole**
## What
Runs `detekt` during the `build` process

<details>
<summary>Images</summary>

</details>

## Changelog Technical Details
+ Added `detekt` runner to the build process. - Daveed & nea

### CODE REVIEW

**Comment by DavidArthurCole** [comment]
With rules that nea and I identified as either being duplicated detekt -> lint, and a couple that were too aggressive, we're down to just over 2100 issues - which is still way too many to be considered 'need to fix'.

So we're likely going to want to define some more customizations in `detekt.yml` to mute some of these before we either do a fix push, or define the baseline.

**Comment by DavidArthurCole** [comment]
Oh, this is gonna happen every beta ._.

**Comment by CalMWolfs** [comment]
> Oh, this is gonna happen every beta ._.

Not if #2558 is merged :)

**Comment by DavidArthurCole** [comment]
```
Execution failed for task ':1.8.9:detekt'.
> Analysis failed with 1527 weighted issues.
```

Down to 1527, progress continues.

**Comment by DavidArthurCole** [comment]
```
Execution failed for task ':1.8.9:detekt'.
> Analysis failed with 981 weighted issues.
```
We're sub-1000, a large portion of which are things that will end up in the `baseline.xml`. Should be able to finish this up in the next couple days.

**Comment by DavidArthurCole** [comment]
We have 121 detections left, all of which I believe can be added to the `baseline.xml`, and safely ignored, or handled separately in the future if someone wants to take action on them.

I'm pulling this out of draft - for actual review, and next steps on this:

There are 370 changed files on this PR, however a vast majority of those were clean-up to get rid of detections, and **should not** be merged. The main packages and files of interest for review are:

- `.github`
- `CONTRIBUTING.MD`
- `build.gradle.kts`
- `/detekt`
- `/gradle/libs.versions.toml`
- `root.gradle.kts`
- `settings.gradle.kts`
- `sharedVariables/src/MinecraftVersion.kt`

Every change in `/src/*` can be ignored.

The merge plan is as follows:
- Generate `baseline.xml`
- Disable `github` detekt workflow (for now)
- Roll-back `/src/*` to HEAD of beta
- Multiple smaller PRs will be opened post-merge to address the hundreds of file changes that need to take place to replicate detection fixing that took place in this PR.

**Comment by DavidArthurCole** [comment]
I think we're also going to need to figure out a way to nerf detekt from completely stopping the build - cause right now `gradlew build` will inevitably fail, and even once we generate the `baseline.xml`, after we reset `/src/`, thousands of errors are going to come back, and would stop anyone from building until they're resolved 🫠

**Comment by hannibal002** [comment]
LGTM.
The build fail needs to go then the pr is ready to get merged IMO

**Pull request merged**
