### PR TITLE
Fixed Custom Keybinds

### PR DESCRIPTION
**Pull request by terriblesitesdemo**
## What
Fixing Custom keybinds

### CODE REVIEW

**Comment by CalMWolfs** [comment]
??? Cheating is not allowed

**Comment by NopoTheGamer** [comment]
?

**Comment by Nealkitt** [comment]
What the .

**Comment by DavidArthurCole** [comment]
Erm, I think you should know; detekt failed 🥺

**Comment by hannibal002** [comment]
Please join our discord so we can have a conversation about this. @terriblesitesdemo

**Pull request closed without merging**
