### PR TITLE
Feature: settings  changes

### PR DESCRIPTION
**Pull request by catgirlseraid**
## Dependencies
- https://github.com/NotEnoughUpdates/MoulConfig/pull/29
- https://github.com/NotEnoughUpdates/MoulConfig/pull/30
- https://github.com/NotEnoughUpdates/MoulConfig/pull/31
- https://github.com/NotEnoughUpdates/MoulConfig/pull/33

## What
Replaced color with colour and armor with armour
reworded some descriptions to make them clearer
added searching color also returns results for colour, same with armor/armour

## Changelog New Features
+ Added ability to search for one word and return results for multiple words. - seraid
    * Used for different spellings.

## Changelog Improvements
+ Reworded some config options. - seraid

## Changelog Technical Details
+ MoulConfig version updated. - seraid

### CODE REVIEW

**Comment by Nealkitt** [comment]
Ready for the American vs British English complaints later? Changing color to colour

**Comment by lunaynx** [comment]
> Ready for the American vs British English complaints later? Changing color to colour

I don't particularly have a strong opinion on the spelling used, but if it's going to break searches for "color", that's bad.

An "additional search keywords" thing like Skytils has for their config may be nice to have.

**Comment by catgirlseraid** [comment]
> > Ready for the American vs British English complaints later? Changing color to colour
> 
> I don't particularly have a strong opinion on the spelling used, but if it's going to break searches for "color", that's bad.
> 
> An "additional search keywords" thing like Skytils has for their config may be nice to have.

yea i agree, i'll see if i can add something like that to the search bar tomorrow

**Review by hannibal002 — DISMISSED** [review]
waiting for `armor -> armour` and `color -> colour` search fix

**Review by CalMWolfs — APPROVED** [review]

**Review by hannibal002 — CHANGES_REQUESTED** [review]
The original scope (fixing typos/better wording) of this pr is done fine and working!

The config version bump adds bugs/unintended changes.
e.g., the search text is positioned off to the left, the highlighted "about" is brighter.
image

At this point, I suggest moving all non armor/color changes into another pr so that can get merged sooner.

**Comment by hannibal002** [comment]
Whats the state of this pr?

**Comment by catgirlseraid** [comment]
> Whats the state of this pr?

i'm fixing moul config bugs, once that's done i'll need to update the moulconfig version here and then it can be merged

i'll mark this pr as a draft for now

**Comment by hannibal002** [comment]
ill move this 0.26

**Review by hannibal002 — CHANGES_REQUESTED** [review]
right clicking on search bar no longer resets the search

**Comment by hannibal002** [comment]
I still recommend we split the us/gb language fix from all other fixes. So that the other fixes can get added already

**Comment by catgirlseraid** [comment]
closed as this has been seperated into multiple prs

pr updating moulconfig
https://github.com/hannibal002/SkyHanni/pull/2737
pr updating language usage is no longer required as the linked pr above solves this

**Pull request closed without merging**
