### PR TITLE
Backend: Add shot support for multi version builds

### PR DESCRIPTION
**Pull request by lineargraph**
## What
Re adds support for shots to add nullability annotations to vanilla code

<details>
<summary>Images</summary>

image

</details>

## Changelog Technical Details
+ Added Shot support to the multi-version build. - !nea
    * This allows adding nullability annotations (and other simple annotations) to vanilla code.

### CODE REVIEW

**Comment by lineargraph** [comment]
cc @CalMWolfs

**Comment by lineargraph** [comment]
Turns out there is quite a bit of code relying on `MC.getMinecraft().thePlayer != null`

**Comment by CalMWolfs** [comment]
> Turns out there is quite a bit of code relying on `MC.getMinecraft().thePlayer != null`

maybe disable the shots from applying right now but ill go through and fix up those cases in the next few days

**Comment by lineargraph** [comment]
Upon further consideration that entire file just belongs commented out lol.

**Review by CalMWolfs — APPROVED** [review]

**Pull request merged**
