### PR TITLE
Bestiary thing

### PR DESCRIPTION
**Pull request by superhize**
Still wip

tips get burried behind inventory but if #348 get merged, it will be fixed

- [x] Add support for main bestiary menu (and fishing sub-category)
   ^ done but not sure about the look

### CODE REVIEW

**Comment by superhize** [comment]
I think i'm done, if anyone want to try, go ahead

**Comment by Jason54jg** [comment]
I think we should add a possibility to click on a bestiary to add it on the screen to see the progress of this mob
also to be able to remove it from the screen

**Comment by hannibal002** [comment]
`tips get burried behind inventory but if https://github.com/hannibal002/SkyHanni/pull/348 get merged, it will be fixed`

#348 is marked as draft

**Comment by superhize** [comment]
> `tips get burried behind inventory but if https://github.com/hannibal002/SkyHanni/pull/348 get merged, it will be fixed`
> 
> #348 is marked as draft

Changed, forgot to change before going to sleep

**Review by hannibal002 — APPROVED** [review]
I did lots of code cleanup

**Pull request merged**
