### PR TITLE
Improvement: Add hover descriptions to many ClickableChat messages

### PR DESCRIPTION
**Pull request by Obsidianninja11**
## What
Adds hover descriptions  to most ClickableChat usages.

## Changelog Improvements
+ Improved many chat message hover descriptions. - Obsidian

### CODE REVIEW

**Comment by hannibal002** [comment]
why exclude_from_changelog

**Comment by Obsidianninja11** [comment]
> why exclude_from_changelog

Thought it wasn't very important to be in changelog, but I removed the exclude

**Comment by Obsidianninja11** [comment]
Thoughts about removing default value from clickableChat()?

**Review by CalMWolfs — APPROVED** [review]

**Comment by Obsidianninja11** [comment]
~~Um, i think something's wrong with the check style thing?~~
nvm the whole function got indented extra somehow

**Pull request merged**
