### PR TITLE
Backend: Preconditions to debug commands

### PR DESCRIPTION
**Pull request by hannibal002**
## What
Added missing in SkyBlock check for debug commands `/shtrackparticles` and in `/shtracksounds`.
Reported: https://discord.com/channels/997079228510117908/1290807590112067668

## Changelog Technical Details
+ Added a missing SkyBlock check for debug commands `/shtrackparticles` and `/shtracksounds`. - hannibal2

### CODE REVIEW

**Comment by martimavocado** [comment]
might be a good idea to add a worldswap check

**Comment by hannibal002** [comment]
> might be a good idea to add a worldswap check

to reset the data?
the "is in sb check" is independent of the world swap event

**Comment by martimavocado** [comment]
to disable/autoend it if the player leaves skyblock

**Review by CalMWolfs — APPROVED** [review]

**Comment by hannibal002** [comment]
> to disable/autoend it if the player leaves skyblock

this is useful, yes. but outside of the scope of this pr.

**Pull request merged**
