### PR TITLE
Add persian SkyHanni support

### PR DESCRIPTION
**Pull request by lineargraph**
## What

Added near eastern inspired config elements

<details>
<summary>Images</summary>

image

</details>

## Changelog New Features
+ Added an April Fools joke - !nea
    * Adds a persian/farsi transliteration of the name "SkyHanni"
    * Adds right aligned category names to the config

exclude_from_changelog

### CODE REVIEW

**Review by CalMWolfs — APPROVED** [review]
worked for me

**Comment by amyulating** [comment]
credit to me for translating it
image

**Review by hannibal002 — APPROVED** [review]
Well, `Honey` is not `Hanni` but it's close enough, I suppose
image

**Comment by lineargraph** [comment]
> Well, `Honey` is not `Hanni` but it's close enough, I suppose image

it is a trans*literation* not a trans*lation*

**Comment by lineargraph** [comment]
i suppose yours works too

**Comment by amyulating** [comment]
هانی doesnt even mean honey
it doesnt mean anything, google translate is shitting itself

**Comment by amyulating** [comment]
as nea said, transliteration
if you want the _translation_, its "عسل آسمانی" (lit. "sky honey" - honey that comes from sky)

**Comment by amyulating** [comment]
@tuxinal whar do you think

**Comment by tuxinal** [comment]
> google translate is shitting itself

tbf that's a decent transliteration _back_ from a transliteration 

but yes "هانی" doesn't mean anything in persian that's only google translate trying to give you a passable answer

**Comment by RayDeeUx** [comment]
https://translate.google.com/?sl=en&tl=fa&text=hannibal&op=translate



pressed backspace a few times and...

https://translate.google.com/?sl=fa&tl=en&text=%D9%87%D8%A7%D9%86%DB%8C&op=translate



seeing as this is a skyblock mod and not a history textbook (plus with this being april fool's day), i'm going to go out on a limb and say that this is fine given the circumstances

**Pull request merged**
