### PR TITLE
Fix: White Enchantments

### PR DESCRIPTION
**Pull request by CalMWolfs**
## What
Fix max enchantments showing as white when the user has sh (and sba) chroma off.

## Changelog Fixes
+ Fixed enchantment colours showing as white when SkyHanni chroma is not enabled. - CalMWolfs

### CODE REVIEW

**Comment by lunaynx** [comment]
Hmm, won't this make both "great" and "perfect" enchants gold by default with chroma off?

**Comment by CalMWolfs** [comment]
> Hmm, won't this make both "great" and "perfect" enchants gold by default with chroma off?

Yes, but both gold is better than one as just white and having people complaining about skyhanni breaking their enchantment colours, the other solutions are to not have chroma by default or to have skyhanni chroma on by default or having enchant parsing off by default. But out of these four, having them both gold seemed like the best option

**Comment by lunaynx** [comment]
Hmm, why not make the perfect fallback another color like purple, or gold and bold? (Though bold is already used for ultimate enchants.)

**Comment by Obsidianninja11** [comment]
> Hmm, why not make the perfect fallback another color like purple, or gold and bold? (Though bold is already used for ultimate enchants.)

I think gold and bold is good.

**Comment by CalMWolfs** [comment]
made it gold and bold

**Pull request merged**
