### PR TITLE
Fix: Hoppity/Choc Factory Updates

### PR DESCRIPTION
**Pull request by DavidArthurCole**
## Dependencies
- https://github.com/hannibal002/SkyHanni-REPO/pull/288
- https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/1437

## What
**THIS _ALSO_ SHOULD NOT BE MERGED UNTIL HOPPITY/CF UPDATE IS OUT**

This PR fixes all issues that arose from the Hoppity/Chocolate Factory update. Very few truly "new" things in here, apart from the bare minimum needed for Chocolate Factory to work.

## Changelog Fixes
+ Fixed malfunctioning Chocolate Factory/Hoppity features due to an update. - Daveed

### CODE REVIEW

**Comment by DavidArthurCole** [comment]
I don't wanna close out of the Client to run detekt, so I'm just gonna hope I went sicko mode, and there are no detektions 🙏

**Comment by DavidArthurCole** [comment]
I suppose that was optimistic

**Comment by DavidArthurCole** [comment]
RAHHHH HYPIXEL CHANGED HITMAN WORDING LAST MINUTE

I gotta fix some stuff

**Comment by DavidArthurCole** [comment]
Crisis adverted (hopefully)

**Review by CalMWolfs — APPROVED** [review]
code seems to look fine, id be happy for this to be merged and then tested in a beta during the next hoppity hunt

**Pull request merged**
