### PR TITLE
fix tps display getting getting too large

### PR DESCRIPTION
**Pull request by PaulProjects**
the tps display looks really bad when it gets too large
and the dark gray for tps under 12 is not really readable, so I changed it to dark red

### CODE REVIEW

**Comment by hannibal002** [comment]
The “Not playable” text was meant as an Easteregg-like thing, but of course, it's more compact and definitely more readable this way.

**Comment by hannibal002** [comment]
image
What happened here? :D

**Comment by PaulProjects** [comment]
ahhhhh... good question
why does github even detect that as change, da heck

**Comment by hannibal002** [comment]
image
IntelliJ thinks you have added one empty line 🤷

**Comment by hannibal002** [comment]
@PaulProjects and your changes are already live in the newest beta.
I could not find you on discord. Wanna send me a pm?

**Pull request merged**
