### PR TITLE
Backend: Create repo patterns and list of patterns

### PR DESCRIPTION
**Pull request by catgirlseraid**
## Dependencies
- https://github.com/hannibal002/SkyHanni/pull/1733

## What
Change anything that should be a repo pattern to a repo pattern.
This includes chat messages and item lore since hypixel can and does change these.
This pr will not add patterns to inventory names or mob names.

v2 pattern groups are added since functionality is changed from match to find for better performance but if they use the same repo pattern every old version of the mod would break

## Changelog Technical Details
+ Added more repo patterns. - seraid

### CODE REVIEW

**Comment by hannibal002** [comment]
Please split this up into smaller PRs, with at most 300 lines changed each

**Comment by ThatGravyBoat** [comment]
> Please split this up into smaller PRs, with at most 300 lines changed each

I do not see a point in splitting this PR up, it is all the same changes, splitting it up is not going to do anything besides have a few more open PRs, there is 0 benefit to splitting it up. 

It changes 2 types of things, moving hardcoded text to patterns and changing certain existing patterns to use more efficient matching/finding, splitting this up does not do anything as they will all be dependent on each other. There is no clean way to split this up.

**Review by ThatGravyBoat — APPROVED** [review]
Code LGTM

**Comment by catgirlseraid** [comment]
closing as after a two month break this pr is too hard to maintain, I will likely redo this as several smaller prs in the future

**Pull request closed without merging**
