### PR TITLE
Fishing Timer Additions

### PR DESCRIPTION
**Pull request by CarsCupcake**
This will add the option to reset the timer from the barn/worm fishing counter.
 Also adds an alert if you hit the 60 worms

### CODE REVIEW

**Comment by hannibal002** [comment]
Why would you want to manually reset this timer? It is intended to show alive time of the oldest mob around you. When you reset the time manually, you will miss some mobs that despawn.

**Comment by CarsCupcake** [comment]
idk, some1 asked me to it, because sometimes while we wormfished a runic mob survived and he wanted then to manualy reset the timer

**Review by hannibal002 — APPROVED** [review]
image
This text is too long, it will shorten it.

image

The sea creature amount will be detected the next tick after the reset happens, effectively not changing the amount. I will rename it.

**Comment by CarsCupcake** [comment]
Ok thank you

**Comment by hannibal002** [comment]
@CarsCupcake do you have discord? I would like to give you the contributor role

**Comment by CarsCupcake** [comment]
yes my id is "carscupcake"

**Pull request merged**
