### PR TITLE
Added toggle for 12hr/24hr in real time hud

### PR DESCRIPTION
**Pull request by Thunderblade73**
This should be the correct branch for it right?

### CODE REVIEW

**Comment by CalMWolfs** [comment]
> This should be the correct branch for it right?

You were close, you want to merge this into Skyhanni:beta from your fork:feature
so you got your one right but you'd want to swap the target branch back to beta

**Comment by hannibal002** [comment]
Changing the base to beta opened up some merge conflicts. but i can fix them myself

**Comment by hannibal002** [comment]
The state of this pr should be fine again.
@Thunderblade73 please look at the changed files tab and confirm to me that this is the final change you want to have in this pr, with nothing missing.

**Comment by hannibal002** [comment]
For the future, please keep your local beta branch clean and up to date. When you start a pr, make a copy branch of your local beta and work in there. Then you don't get confusing merge conflicts.

**Comment by Thunderblade73** [comment]
I can confirm that the pr is finished now. 
And sry for the branch issue.

**Review by hannibal002 — CHANGES_REQUESTED** [review]
`realTimeFormatToggle` should not have `@FeatureToggle`.

This toggle is only meant for standalone features that users might want to enable/disable by default, not for options that change the behavior of said feature.

**Comment by Thunderblade73** [comment]
Ok, removed it again. Didn`t know about that. I just copy and pastet it :)
Now it is fine

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
