### PR TITLE
Fixes golden gift treated as a gift

### PR DESCRIPTION
**Pull request by mastermindgolem**
Fixes https://discord.com/channels/997079228510117908/1183800317855408128/1183800317855408128

### CODE REVIEW

**Comment by lunaynx** [comment]
This is a cleaner way to do it, and will ensure any possible future items containing `[WHITE|GREEN|RED]_GIFT` won't be misdetected as winter gifts:
```diff
diff --git a/src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt b/src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
index fd880222..6714514f 100644
--- a/src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
+++ b/src/main/java/at/hannibal2/skyhanni/features/event/UniqueGiftingOpportunitiesFeatures.kt
@@ -13,6 +13,7 @@ import at.hannibal2.skyhanni.utils.EntityUtils.isNPC
 import at.hannibal2.skyhanni.utils.InventoryUtils
 import at.hannibal2.skyhanni.utils.LorenzColor
 import at.hannibal2.skyhanni.utils.LorenzUtils
+import at.hannibal2.skyhanni.utils.NEUInternalName.Companion.asInternalName
 import at.hannibal2.skyhanni.utils.StringUtils.matchMatcher
 import at.hannibal2.skyhanni.utils.getLorenzVec
 import net.minecraft.client.entity.EntityPlayerSP
@@ -28,6 +29,10 @@ object UniqueGiftingOpportunitiesFeatures {

     private val pattern = "§6\\+1 Unique Gift given! To ([^§]+)§r§6!".toPattern()

+    private val giftItemIds = arrayOf("WHITE_GIFT", "GREEN_GIFT", "RED_GIFT").map {
+        it.asInternalName()
+    }.toTypedArray()
+
     private fun hasGiftedPlayer(player: EntityPlayer) = playerList?.contains(player.name) == true

     private fun addGiftedPlayer(playerName: String) {
@@ -37,9 +42,7 @@ object UniqueGiftingOpportunitiesFeatures {
     private val config get() = SkyHanniMod.feature.event.winter.giftingOpportunities

     private fun isEnabled() = LorenzUtils.inSkyBlock && config.enabled &&
-        (InventoryUtils.itemInHandId.contains("WHITE_GIFT") ||
-        InventoryUtils.itemInHandId.contains("GREEN_GIFT") ||
-        InventoryUtils.itemInHandId.contains("RED_GIFT")
+        (giftItemIds.contains(InventoryUtils.itemInHandId)
             || !config.highlighWithGiftOnly)

     private val hasNotGiftedNametag = "§a§lꤥ"
```

**Comment by martimavocado** [comment]
this also breaks for `WHITE_GIFT_TALISMAN`, `GREEN_GIFT_TALISMAN` and `RED_GIFT_TALISMAN`

**Comment by lineargraph** [comment]
Just use a repo regex so we can change the pattern later smiles

**Comment by CalMWolfs** [comment]
this hasnt been updated in a while so made new pr with it as repo pattern
https://github.com/hannibal002/SkyHanni/pull/875

**Comment by hannibal002** [comment]
Closing as https://github.com/hannibal002/SkyHanni/pull/875 got merged already.

**Pull request closed without merging**
