### PR TITLE
Improvement: import egg locations from NEU PV

### PR DESCRIPTION
**Pull request by appable0**
## Dependencies
- https://github.com/hannibal002/SkyHanni-REPO/pull/207

## What
Allows players to import their collected egg locations from the API using the NEU Profile Viewer, analogous to the existing trophy fishing import feature.

Also adds an egg location viewer for development, toggled with `/shtoggleegglocationdebug`, which shows the internal names and coordinates for each waypoint (see screenshot).

Currently a draft because some API names need to be confirmed; see dependent PR for details.

<details>
<summary>Images</summary>
API import clickable chat:
Screenshot 2024-05-31 at 9 17 38 PM

Development viewer:
Screenshot 2024-05-31 at 9 12 48 PM

</details>

## Changelog Improvements
+ Added collected egg location API import. - appable
    * Open your NEU profile viewer and click the chat message to load data.

### CODE REVIEW

**Review by CalMWolfs — APPROVED** [review]
worked for me

**Comment by jani270** [comment]
Feature works great, just one little thing:
image

Not sure if we want to keep it that way

**Comment by CalMWolfs** [comment]
> Feature works great, just one little thing
> Not sure if we want to keep it that way

Yeah, it isnt ideal, but it also does that without this pr so that should probably be adressed elsewhere

**Comment by appable0** [comment]
I could try some other formats (underneath and smaller than the main label?), but I'd prefer to keep this PR limited in scope unless it's urgently felt that this needs to change.

**Comment by hannibal002** [comment]
"show all eggs" is only meant as a debug/irst spring feature. we can remove the thingy/move into dev, instead of trying to make a feature no longer meant for users more appealing for users

**Pull request merged**
