### PR TITLE
Feature: Reforge helper

### PR DESCRIPTION
**Pull request by Thunderblade73**
## Dependencies
- #822
- #821
- #811
-  #746 
- #846 
- #885 
- #890 
- #1191
- #888 
# What
A helper for random Reforges similar to the one sba has but better.
Blocks the Reforge Button when the desired reforge is on the item.
Shows all possible Reforges, with there stats and the difference it would make by chancing to them
and has support for reforge stones in Hex
# Preview
image

## Changelog New Features
+ Reforge Helper. - Thunderblade73
    * Adds reforge locking similar to sba
    * Works with Hex
    * Gives a list of all possible reforge for the item, with stats
    * The reforge list can be sorted for a specific stat
## Changelog Technical Details
+ Added SkyblockStats - Thunderblade73
+ Added ReforgeAPI - Thunderblade73

### CODE REVIEW

**Comment by Thunderblade73** [comment]
Dependencies are:
- [ ] #829
- [ ] #822
- [ ] #821
- [ ] #811
- [ ] #746

**Comment by hannibal002** [comment]
Does this only work in hex, or also in reforge anvil?

**Comment by Thunderblade73** [comment]
it works in hex, at the blacksmith, at the dungeon reforge thing and in the reforge anvil in privat island if on random reforge. 
In the reforge anvil itself it doesn't work, because I do not see any reason why it should work there, since it is only used to combine stuff (and you need the stuff before)

**Comment by Thunderblade73** [comment]
continued in #1437

**Pull request closed without merging**
