### PR TITLE
Basic styled replace

### PR DESCRIPTION
**Pull request by lineargraph**
## Dependencies
- pr_number_or_link_here

## What
Describe what this pull request does, including technical details, screenshots, links to discord, etc.

<details>
<summary>Images</summary>

</details>

## Changelog New Features
+ Cool new feature. - your_name_here
    * extra info

## Changelog Improvements
+ Improved cool feature. - your_name_here
    * Extra info.

## Changelog Fixes
+ Fixed cool feature. - your_name_here
    * Extra info.

## Changelog Technical Details
+ Something technical you changed in the backend. - your_name_here
    * Extra info.

## Changelog Removed Features
+ Removed cool feature. - your_name_here
    * Extra info.

### CODE REVIEW

**Comment by hannibal002** [comment]
I know this is still a draft, wanted to give feedback still:
image

**Comment by lineargraph** [comment]
I am not sure if i am super interested in working on this tbh.

**Comment by hannibal002** [comment]
totally fine. ill just use a workaround for now then

**Comment by hannibal002** [comment]
https://github.com/hannibal002/SkyHanni/pull/1680

**Pull request closed without merging**
