### PR TITLE
Account upgrade complete reminder

### PR DESCRIPTION
**Pull request by appable0**
This pull request adds a simple reminder when an account upgrade is completed, modeled heavily on city project reminders. Enabled by default; can be disabled in settings or by clicking.

TODO is to merge the city project reminder logic with this and potentially other reminders, as it's definitely a bit duplicated currently.

### CODE REVIEW

**Review by hannibal002 — CHANGES_REQUESTED** [review]
I think the value `durationDays` could not get loaded for me:
image

**Comment by hannibal002** [comment]
```
Search config for SkyHanni 0.20.Beta.6
configSearchTerm: 'account'
classSearchTerm: <all>

Found 3 config elements:
config.misc.accountUpgradeReminder Boolean = true
playerSpecific.currentAccountUpgrade String = 'Garden Farming Fortune IX'
playerSpecific.nextAccountUpgradeCompletionTime Long = 1.689.817.262.687
```

**Comment by appable0** [comment]
Hmm, worked for my account but only got one chance to test. I'll look into this in a few days when my alt has an upgrade ready; marking as a draft for now.

**Review by hannibal002 — APPROVED** [review]
It worked for me now in my 2. account

**Pull request merged**
