### PR TITLE
Add check for new regexes before updating repo

### PR DESCRIPTION
**Pull request by lineargraph**

### CODE REVIEW

**Review by jani270 — COMMENTED** [review]
amazing pr, would recommend merging

**Comment by lineargraph** [comment]
> amazing pr, would recommend merging

terrible pr, actually, please do not merge

**Comment by jani270** [comment]
even after one (scary) force push this pr is amazing

**Comment by lineargraph** [comment]
> even after one (scary) force push this pr is amazing

how about two force pushes

**Comment by jani270** [comment]
😨 Another scary force push

**Comment by jani270** [comment]
we should consider disabling force pushes here, they are too scary 😨

**Comment by lineargraph** [comment]
> we should consider disabling force pushes here, they are too scary 😨

Fun fact: you can't :)

**Comment by jani270** [comment]
then i will block everyone who uses force push

**Review by hannibal002 — APPROVED** [review]

**Comment by jani270** [comment]
holy shit 1 approve

**Comment by jani270** [comment]
and a merge WTF

**Pull request merged**
