### PR TITLE
Wrong/broken Changelog: Fix wrong crop milestone being displayed when using mismatched tool

### PR DESCRIPTION
**Pull request by lunaynx**

### CODE REVIEW

**Comment by lunaynx** [comment]
Hmm, when I farm cactus with cactus knife and then switch to advanced gardening hoe, it still shows cactus milestone until I break another crop. This might be fine though.

**Comment by lunaynx** [comment]
Ugh, this seems to cause issues sometimes. It should probably reset the last broken crop when switching tools. I just got this after buying a melon dicer after farming mushrooms:
```
SkyHanni 0.23.Beta.18: Unknown dicer: Mushroom
 
Caused by kotlin.collections.builders.ListBuilder: Unknown dicer: Mushroom
	at SH.test.command.ErrorManager.skyHanniError(ErrorManager.kt:25)
	at SH.features.garden.farming.CropMoneyDisplay.drawDisplay(CropMoneyDisplay.kt:151)
	at SH.features.garden.farming.CropMoneyDisplay.update(CropMoneyDisplay.kt:94)
	at SH.features.garden.farming.CropMoneyDisplay.onGardenToolChange(CropMoneyDisplay.kt:78)
	at FML.common.eventhandler.ASMEventHandler_897_CropMoneyDisplay_onGardenToolChange_GardenToolChangeEvent.invoke(.dynamic)
	at FML.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at SH.events.LorenzEvent.postAndCatchAndBlock(LorenzEvent.kt:43)
	at SH.events.LorenzEvent.postAndCatchAndBlock$default(LorenzEvent.kt:31)
	at SH.events.LorenzEvent.postAndCatch(LorenzEvent.kt:19)
	at SH.features.garden.GardenAPI.updateGardenTool(GardenAPI.kt:118)
	at SH.features.garden.GardenAPI.checkItemInHand(GardenAPI.kt:129)
	at SH.features.garden.GardenAPI.onTick(GardenAPI.kt:103)
	at FML.common.eventhandler.ASMEventHandler_416_GardenAPI_onTick_LorenzTickEvent.invoke(.dynamic)
	at FML.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at SH.events.LorenzEvent.postAndCatchAndBlock(LorenzEvent.kt:43)
	at SH.events.LorenzEvent.postAndCatchAndBlock$default(LorenzEvent.kt:31)
	at SH.events.LorenzEvent.postAndCatch(LorenzEvent.kt:19)
	at SH.data.MinecraftData.onTick(MinecraftData.kt:74)
	at FML.common.eventhandler.ASMEventHandler_302_MinecraftData_onTick_ClientTickEvent.invoke(.dynamic)
	at FML.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at FML.common.eventhandler.EventBus.post(EventBus.java:140)
	at FML.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at MC.client.Minecraft.func_71407_l(Minecraft.java:2151)
	at MC.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at MC.client.Minecraft.handler$zjp000$run(Minecraft.java:3250)
	at MC.client.Minecraft.func_99999_d(Minecraft.java)
	at MC.client.main.Main.main(SourceFile:124)
	at MC.launchwrapper.Launch.launch(Launch.java:135)
	at MC.launchwrapper.Launch.main(Launch.java:28)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at java.lang.Class.newInstance(Class.java:442)
	at MC.launchwrapper.Launch.launch(Launch.java:98)
	at MC.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by lunaynx** [comment]
Actually, I think that wouldn't fix it if someone decides to farm another crop with their melon/pumpkin dicer, so a different fix is needed.

**Comment by hannibal002** [comment]
old

**Pull request closed without merging**
