### PR TITLE
Improvement: Disable Lane Switch notifications while flying

### PR DESCRIPTION
**Pull request by lunaynx**
## What
Disable lane switch notifications while flying.

## Changelog Improvements
+ Disable lane switch notifications while flying. - Alexia Luna

### CODE REVIEW

**Comment by ItsEmpa** [comment]
not a huge fan of this, what if at some point theres a farm design you need to fly in? i feel like it would be better to disable the notifications if you arent holding any farming tool

**Comment by hannibal002** [comment]
I thought we already checked this by isFarming (> 0 bps).
Maybe we should check in isFarming if the time since farming is greater than one second or something.

Maybe users want to fly through their farms, then this feature should work fine as well imo.
Not that we actively support fly farming, i just dont think this is the right approach to fixing this

**Comment by lunaynx** [comment]
Flying has never been meta since the old lazy farm days. It's messy because you don't accelerate to full speed immediately and you can't really control your speed beyond sprinting or not sprinting. It's highly unlikely for it to become meta again, and if it somehow does, we can change it then.

Simply checking for holding a farming tool could still lead to false notifications while people are trying to get positioned, especially since the crop start location only shows while holding a tool, for example.

**Comment by ItsEmpa** [comment]
well then probably like hanni said, using the isCurrentlyFarming() check

**Comment by hannibal002** [comment]
No longer necessary since https://github.com/hannibal002/SkyHanni/pull/1208 fixed those problems

**Pull request closed without merging**
