### PR TITLE
Feature: Dungeon party finder QOL improvements

### PR DESCRIPTION
**Pull request by brandonwamboldt**
Got fed up with dungeon finder lately and made some quick QOL improvements

- Show floor as stack size in case you aren't filtering for specific floors
- Mark paid carries with a red background
- Mark groups you aren't eligible for with a dark red background (sure you can change your search settings to not get these groups but you'd have to remember to keep updating your search settings as you level)
- Mark groups with players below a specified level with a yellow background
- Mark groups that don't have a player of your selected dungeon class with a green background

Overall should make dungeon finder less annoying to use 

java_2023-10-04_16-41-33
java_2023-10-04_16-40-00
javaw_2023-10-04_16-52-11
javaw_2023-10-05_11-49-28
javaw_2023-10-05_11-50-00

### CODE REVIEW

**Comment by hannibal002** [comment]
> Show floor as stack size in case you aren't filtering for specific floors

Ery will be mad im sure :D

**Comment by hannibal002** [comment]
Also, most of this stuff is already in Cowlection I'm sure.
So IDK if we should add them. Since you already wrote it, I think giving the users more options isn't bad.

**Comment by brandonwamboldt** [comment]
I did check Cowlection first and it has a configurable regex/text engine for filtering groups, so you can accomplish some of the same stuff if you setup your own rules, but can't do stuff like highlight groups missing your own class or groups with users lower then a certain level (unless you setup a bunch of unwieldy regexes). I think both sets of party finder features provide different functionality (its why i didnt add anything to filter out based on custom criteria though).

**Comment by RayDeeUx** [comment]
> > Show floor as stack size in case you aren't filtering for specific floors
> 
> Ery will be mad im sure :D

not even close

if anything, mort the dungeon menu was something i completely skipped during my stack size writing process.

finders keepers though—let them have this one

**Comment by hannibal002** [comment]
> I did check Cowlection first and it has a configurable regex/text engine for filtering groups, so you can accomplish some of the same stuff if you setup your own rules, but can't do stuff like highlight groups missing your own class or groups with users lower then a certain level (unless you setup a bunch of unwieldy regexes). I think both sets of party finder features provide different functionality (its why i didnt add anything to filter out based on custom criteria though).

This is fair! Will move to 0.21

**Comment by brandonwamboldt** [comment]
@hannibal002 merge conflicts resolved

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
