### PR TITLE
Backend: True Defense spelling

### PR DESCRIPTION
**Pull request by jani270**
## What
Fixes the spelling of true defense that causes a error on neureloadrepo. @Thunderblade73 stop throwing pls 🧌 

## Changelog Technical Details
+ Fixed spelling of True Defense in SkyblockStat. - jani

### CODE REVIEW

**Comment by jani270** [comment]
bro really

**Comment by jani270** [comment]
i will just delete the changelog verify workflow

**Review by hannibal002 — CHANGES_REQUESTED** [review]
This needs a config fix event for `ProfileStorageData.profileSpecific?.stats`

**Comment by jani270** [comment]
Too much effort someone else can do it then

**Comment by jani270** [comment]
Crazy system you got there, really fun to worth with

**Comment by hannibal002** [comment]
https://github.com/hannibal002/SkyHanni/commit/755f7f51a7040ab18bb6fe5539914c1a8a5c59df

**Comment by NopoTheGamer** [comment]
💀

**Comment by jani270** [comment]
> [755f7f5](https://github.com/hannibal002/SkyHanni/commit/755f7f51a7040ab18bb6fe5539914c1a8a5c59df)

Thats even more crazy, i love having errors in my chat while working with the repo.

**Comment by jani270** [comment]
grafik
found a better way. this will be fun 👍

**Pull request closed without merging**
