### PR TITLE
Backend: Renderable scrollables

### PR DESCRIPTION
**Pull request by Thunderblade73**
## Dependencies
- #885 
# What
Adds Scrolllist and Scrolltable. Those make it possible to have scrolling content in any GUI.

## Changelog Technical Details
+ Added scroll able logic for Renderables. - Thunderblade73
    * Added elements: scrollList and scrollTable.

### CODE REVIEW

**Comment by hannibal002** [comment]
I have tested this pr with https://github.com/hannibal002/SkyHanni/pull/1334


image
image

Does not work. Am i using it correctly?

**Review by hannibal002 — CHANGES_REQUESTED** [review]
see above

**Comment by Thunderblade73** [comment]
Fixed the bug (and improved the list a bit). 
I have never used the list version, only used the table version therefore it was a bit bugged. 
The issue was that I used a maxOf instead of a sumOf 😅 and that I never checked the end bound.

**Review by hannibal002 — APPROVED** [review]
works in the other pr

**Pull request merged**
