### PR TITLE
Fix: OneConfig listing SkyHanni twice in their modlist

### PR DESCRIPTION
**Pull request by martimavocado**
## What
fixes oneconfig showing skyhanni twice
image
still doesn't show the logo but that's an issue on their end

## Changelog Fixes
+ Fixes OneConfig listing SkyHanni twice. - martimavocado

### CODE REVIEW

**Comment by hannibal002** [comment]
I dont like this workaround. should be fixed by oneconfig instead.
since you know how to fix this in skyhanni, and oneconfig is open source, can you fix this for them directly?

**Comment by martimavocado** [comment]
i talked with them, they linked me to [IgnoredGuiFactory](https://github.com/Polyfrost/OneConfig/blob/develop/versions/src/main/java/cc/polyfrost/oneconfig/utils/IgnoredGuiFactory.java) which looks like their "intended" solution according to the comments, i don't know what there is to fix on their side about this, except maybe not letting the same modid create a config twice? but this is used in a bunch of their mods

**Comment by hannibal002** [comment]
I'm against OneConfig soft-depend support for their config manager. And in the same way, I'm against supporting OneConfig by fixing their bugs with this solution.

After merging this, one might look at the SkyHanni packets and think we are linked to OneConfig in any way. I don't want that.

**Comment by martimavocado** [comment]
that's fair

**Pull request closed without merging**
