### PR TITLE
Refactor: Clean up pluralization methods

### PR DESCRIPTION
**Pull request by lunaynx**

### CODE REVIEW

**Comment by hannibal002** [comment]
Why can the second string parameter "plural" be null?

**Comment by lunaynx** [comment]
If it's null, it just falls back to `${singular}s`. It felt weird to make the default an empty string, but I can do that instead if you prefer.

**Comment by hannibal002** [comment]
I have not see this


plural ?: "${singular}s"


This is fine, leave it default null

**Review by CalMWolfs — APPROVED** [review]
lgtm

**Pull request merged**
