### PR TITLE
Backend: Re-Enable Style Checking Workflow

### PR DESCRIPTION
**Pull request by DavidArthurCole**
## What
Re-enable the `check-style` workflow, as it's back to working correctly.
Tested runner [here](https://github.com/DavidArthurCole/SkyHanni/actions/runs/10784841705/job/29909098361).

exclude_from_changelog

### CODE REVIEW

**Comment by DavidArthurCole** [comment]
And of course it doesn't work on the PR into the repo 🙃
More to come - as I've been digging at this...

**Comment by DavidArthurCole** [comment]
Oh. It didn't fail to work.
It correctly identified a whole shitload of bad formatting since it's been disabled.

Don't know what we wanna do about that ...

**Comment by hannibal002** [comment]
this file is 404 for me

> Could not GET 'https://maven.deftu.xyz/releases/dev/deftu/preprocessor/0.6.1/preprocessor-0.6.1.jar'.

**Comment by j10a1n15** [comment]
> this file is 404 for me
> 
> 
> 
> > Could not GET 'https://maven.deftu.xyz/releases/dev/deftu/preprocessor/0.6.1/preprocessor-0.6.1.jar'.

[every pr has that rn](https://github.com/hannibal002/SkyHanni/pull/2490)

**Comment by hannibal002** [comment]
> Don't know what we wanna do about that ...

Can we make it only check changed files?
If not, we should disable the most commonly flagged rules, and fix the remaining bugs immediately. Then over time, re-enable the rules again.

**Comment by lineargraph** [comment]
There is a discussion regarding using detekt (which allows for creation of baseline files): https://discord.com/channels/997079228510117908/1250434494473834597. Might make sense to implement all of that in one go

**Comment by DavidArthurCole** [comment]
Closing this in favor of #2547

**Pull request closed without merging**
