### PR TITLE
SkyHanni - berberis coordinate chat message

### PR DESCRIPTION
**Pull request by tfoskeehc**
send chat message of berberis bush's coordinates

### CODE REVIEW

**Comment by CalMWolfs** [comment]
Don't have time to explain more now but you have done a few things wrong. 
1. There are a lot of changes here that you didn't mean to commit
2. Make a new branch for your changes don't use beta. This probably contributed to the above problem
3. I don't see an option to turn this message on or off

**Comment by hannibal002** [comment]
I will mark this as a draft until the the points cal talked about were fixed.
You can change the pr to "ready to review" yourself on the GitHub page of this pr later.

**Review by lineargraph — APPROVED** [review]
I am head of SkyHannis cheating development team, and I approve this PR!

**Comment by hannibal002** [comment]
we arent a js module or support baritone

**Comment by RayDeeUx** [comment]
630 files changed 💀

**Pull request closed without merging**
