### PR TITLE
Backend: Change the detekt rule to be more generalised

### PR DESCRIPTION
**Pull request by CalMWolfs**
exclude_from_changelog

### CODE REVIEW

**Review by DavidArthurCole — APPROVED** [review]
Forgot to actually review this - LGTM.

**Review by hannibal002 — CHANGES_REQUESTED** [review]
cant get this working. neither in string, nor in variable name, not in kt or java files

**Comment by DavidArthurCole** [comment]
> cant get this working. neither in string, nor in variable name, not in kt or java files

I think I know why 🥺 

`/detekt/detekt.yml`
```
GrammarRules:
    active: true
    AvoidColour: # custom rule to prefer color to colour
        active: true
```

**Comment by DavidArthurCole** [comment]
Yuh
image

**Pull request merged**
