### PR TITLE
Improvement: Jacob's Contest Numbers on Custom Scoreboard

### PR DESCRIPTION
**Pull request by DavidArthurCole**
## What
Formats numbers relating to Jacob's contest with the user selected number format for the Custom Scoreboard.

<details>
<summary>Images</summary>

Old:
image

New:
image
image

</details>

## Changelog Improvements
+ Improved formatting of Jacob's Contest data on Custom Scoreboard. - Daveed

### CODE REVIEW

**Review by hannibal002 — CHANGES_REQUESTED** [review]
The logic belongs into farming contest API.

Why is the existing pattern for detecting the scoreboard lines not sufficient? Aren't we already showing all contest lines in the custom scoreboard? This feels like code duplication to me right now. I'm sure I'm missing something, please elaborate.

**Comment by j10a1n15** [comment]
> The logic belongs into farming contest API.
> 
> Why is the existing pattern for detecting the scoreboard lines not sufficient? Aren't we already showing all contest lines in the custom scoreboard? This feels like code duplication to me right now. I'm sure I'm missing something, please elaborate.

This directly adds onto the Jacobs Event Entry. We detect the Jacobs lines using .nextAfter(), not patterns. There is no code duplication on the Scoreboard End

**Comment by DavidArthurCole** [comment]
> The logic belongs into farming contest API.
> 
> 
> 
> Why is the existing pattern for detecting the scoreboard lines not sufficient? Aren't we already showing all contest lines in the custom scoreboard? This feels like code duplication to me right now. I'm sure I'm missing something, please elaborate.

As noted, this is new functionality to the custom scoreboard - it was using .nextAfter() to pull event data lines, meaning the formatting of numbers did not adhere to the custom scoreboard setting that affects things like bank, purse, copper, bits, etc.

So I'd second the challenge that this is duplicated code

**Comment by DavidArthurCole** [comment]
Closing this since Hypixel copied my PR on Alpha

> - Shortened the length of the text for the # of crops you have harvested on the scoreboard during Jacob's Contests
>     - Crops will now display in shorthand form in the scoreboard, ex) 1,234,567 -> 1.23M

**Pull request closed without merging**
