### PR TITLE
Backend: Reworded a previous commit

### PR DESCRIPTION
**Pull request by NeoNyaa**
Reworded a poorly written sentence from a previous pull req of mine.

Prettier auto formatted CONTRIBUTING.md, hope this isn't an issue. I can undo this if need be.

## Changelog Technical Details
+ Reworded a poorly written sentence in CONTRIBUTING.md. - NeoNyaa

exclude_from_changelog

### CODE REVIEW

**Comment by hannibal002** [comment]
Your PR adds new spaces in front of many lines. I don't think this is intended. 
image

**Comment by NeoNyaa** [comment]
> Your PR adds new spaces in front of many lines. I don't think this is intended. image

Yea thats prettier doing that

**Comment by hannibal002** [comment]
does this look different on github? we use the same style for every md file

**Comment by NeoNyaa** [comment]
> does this look different on github? we use the same style for every md file

I believe it doesnt look different but I can make a commit without the formatting if thats preffered

**Comment by hannibal002** [comment]
Yes, please change it back to the old format

**Review by NeoNyaa — COMMENTED** [review]
Prettier formatting removed as requested

**Pull request merged**
