### PR TITLE
Feature: Display Tab Widgets

### PR DESCRIPTION
**Pull request by Thunderblade73**
## Dependencies
- #1150

## What
Makes it possible to display any Tab Widget on the HUD. It only needs an entry in the enum TabWidgetDisplay

<details>
<summary>Images</summary>

image
</details>

## Changelog New Features
+ Added Display Tab Widgets. - Thunderblade73
    * Allows the display of information from the Tab (e.g., Bestiary info).

### CODE REVIEW

**Comment by hannibal002** [comment]
image

**Review by CalMWolfs — APPROVED** [review]

**Review by hannibal002 — CHANGES_REQUESTED** [review]
```
RepoPatternTest > testRemoteLoadGroupButNotFromList() FAILED
    java.util.ConcurrentModificationException at RepoPatternTest.kt:174
```

**Comment by Thunderblade73** [comment]
> ```
> RepoPatternTest > testRemoteLoadGroupButNotFromList() FAILED
>     java.util.ConcurrentModificationException at RepoPatternTest.kt:174
> ```

https://github.com/hannibal002/SkyHanni/pull/2098

**Review by hannibal002 — CHANGES_REQUESTED** [review]
looks already good!

It seems the event trackers arent added though, therefore the data gets merged to coins
image


<details>
<summary>/shcopytablist</summary>

Header:

§r§bYou are playing on §r§e§lMC.HYPIXEL.NET§r
§r§r§r§r§s§r

Body:

'         §r§a§lPlayers §r§f(23)'
'§8[§r§6419§r§8] §r§bhannibal2 §r§7☢'
'§8[§r§5386§r§8] §r§bScratchSkittlez §r§5§l࿇'
'§8[§r§d341§r§8] §r§bPiskotek1379 §r§7α§r§7♲'
'§8[§r§3278§r§8] §r§bArcticKomet §r§b§lᛝ'
'§8[§r§3278§r§8] §r§bSlaydemall §r§7§lツ§r§7♲'
'§8[§r§2192§r§8] §r§bSeNuuup §r§6§lᛝ'
'§8[§r§720§r§8] §r§bKekse4free §r§5Ⓑ'
'§8[§r§726§r§8] §r§bxASF100 §r§6Ⓑ'
'§8[§r§a149§r§8] §r§bvaduz12ru'
'§8[§r§a134§r§8] §r§bFiero123'
'§8[§r§f52§r§8] §r§bbenutzername007 §r§7♲'
'§8[§r§3242§r§8] §r§aGAMBLEDEDICATION §r§6ௐ'
'§8[§r§b213§r§8] §r§aCodmax §r§6§lᛝ'
'§8[§r§711§r§8] §r§aSashaN12 §r§7Ⓑ'
'§8[§r§2176§r§8] §r§7Rc2000 §r§6§lꤥ'
'§8[§r§f64§r§8] §r§7Greeceman123'
'§8[§r§f49§r§8] §r§7GSOHTT'
'§8[§r§724§r§8] §r§7Kremos_Gaming §r§7♲'
'§7and 5 other players...'
'               §r§3§lInfo'
'§b§lArea: §r§7Dwarven Mines'
' Server: §r§8mini9DQ'
' Gems: §r§a430'
' Fairy Souls: §r§d14§r§5/§r§d14'
'§9§lCommissions:'
' §r§fRaffle: §r§c0%'
' §r§fGolden Goblin Slayer: §r§c0%'
' §r§fTreasure Hoarder Puncher: §r§a80%'
' §r§fRampart's Quarry Mithril: §r§c0%'
'§9§lForges:'
' 1) §r§f§r§6Refined Titanium§r§7: §r§aReady!'
' 2) §r§f§r§6Refined Titanium§r§7: §r§aReady!'
' 3) §r§f§r§6Refined Titanium§r§7: §r§aReady!'
' 4) §r§f§r§6Refined Titanium§r§7: §r§aReady!'
' 5) §r§f§r§6Refined Titanium§r§7: §r§aReady!'
'               §r§3§lInfo'
'§9§lPowders:'
' Mithril: §r§2292,385'
' Gemstone: §r§d213,333'
' Glacite: §r§b1,351,833'
'§l§r§e§lProfile: §r§aZucchini'
' SB Level§r§f: §r§8[§r§6419§r§8] §r§b53§r§3/§r§b100 XP'
' Bank: §r§61B§r§7 / §r§6202M'
' Interest: §r§e13 Hours§r§6 (706k)'
'§e§lEvent Trackers:'
' Mythological Kills: §r§a29'
' Inquisitor Kills: §r§a0'
' Burrows Dug: §r§a52'
'               §r§3§lInfo'
'§8[§720§8] §bKekse4free §5Ⓑ'
'§8[§726§8] §bxASF100 §6Ⓑ'
'§8[§3278§8] §bArcticKomet §b§lᛝ'
'§8[§5386§8] §bScratchSkittlez §5§l࿇'
'§8[§d341§8] §bPiskotek1379 §7α§7♲'
'§8[§3278§8] §bSlaydemall §7§lツ§7♲'
'§8[§2192§8] §bSeNuuup §6§lᛝ'
'§8[§6419§8] §bhannibal2 §7☢'
'§8[§a134§8] §bFiero123'
'§8[§a149§8] §bvaduz12ru'
'§8[§f52§8] §bbenutzername007 §7♲'
'§8[§3242§8] §aGAMBLEDEDICATION §6ௐ'
'§8[§711§8] §aSashaN12 §7Ⓑ'
'§8[§b213§8] §aCodmax §6§lᛝ'
'§8[§f64§8] §7Greeceman123'
'§8[§713§8] §7ToWiZzZ'
'§8[§f49§8] §7GSOHTT'
'§8[§711§8] §7zhe_chicken24'
'§8[§720§8] §7iTzzzGustazz'
'§8[§717§8] §7KisskittleJava'
'§8[§724§8] §7Kremos_Gaming §7♲'
'§8[§711§8] §7HamzaAhamad §7Ⓑ'

Footer:

§r
§r§r§a§lActive Effects§r
§r§r§7You have a §r§cGod Potion §r§7active! §r§d12 Hours§r
§r§r§7You have §r§e1 §r§7non-god effects.§r
§r§r§7Use "§r§6/effects§r§7" to see them!§r
§r§r§2Glowing Mush Mixin I§r§r§r §r§f26h§r
§r§r§r§r§s§r
§r§r§d§lCookie Buff§r
§r§r§f3 years, 1 month§r
§r§r§r§r§s§r
§r§r§aRanks, Boosters & MORE! §r§c§lSTORE.HYPIXEL.NET§r

Widgets:
PLAYER_LIST : 
         §r§a§lPlayers §r§f(23)
§8[§r§6419§r§8] §r§bhannibal2 §r§7☢
§8[§r§5386§r§8] §r§bScratchSkittlez §r§5§l࿇
§8[§r§d341§r§8] §r§bPiskotek1379 §r§7α§r§7♲
§8[§r§3278§r§8] §r§bArcticKomet §r§b§lᛝ
§8[§r§3278§r§8] §r§bSlaydemall §r§7§lツ§r§7♲
§8[§r§2192§r§8] §r§bSeNuuup §r§6§lᛝ
§8[§r§720§r§8] §r§bKekse4free §r§5Ⓑ
§8[§r§726§r§8] §r§bxASF100 §r§6Ⓑ
§8[§r§a149§r§8] §r§bvaduz12ru
§8[§r§a134§r§8] §r§bFiero123
§8[§r§f52§r§8] §r§bbenutzername007 §r§7♲
§8[§r§3242§r§8] §r§aGAMBLEDEDICATION §r§6ௐ
§8[§r§b213§r§8] §r§aCodmax §r§6§lᛝ
§8[§r§711§r§8] §r§aSashaN12 §r§7Ⓑ
§8[§r§2176§r§8] §r§7Rc2000 §r§6§lꤥ
§8[§r§f64§r§8] §r§7Greeceman123
§8[§r§f49§r§8] §r§7GSOHTT
§8[§r§724§r§8] §r§7Kremos_Gaming §r§7♲
§7and 5 other players...

INFO : 
               §r§3§lInfo

AREA : 
§b§lArea: §r§7Dwarven Mines

SERVER : 
 Server: §r§8mini9DQ

GEMS : 
 Gems: §r§a430

FAIRY_SOULS : 
 Fairy Souls: §r§d14§r§5/§r§d14

PROFILE : 
§l§r§e§lProfile: §r§aZucchini

SB_LEVEL : 
 SB Level§r§f: §r§8[§r§6419§r§8] §r§b53§r§3/§r§b100 XP

BANK : 
 Bank: §r§61B§r§7 / §r§6202M

INTEREST : 
 Interest: §r§e13 Hours§r§6 (706k)
§e§lEvent Trackers:
 Mythological Kills: §r§a29
 Inquisitor Kills: §r§a0
 Burrows Dug: §r§a52

FORGE : 
§9§lForges:
 1) §r§f§r§6Refined Titanium§r§7: §r§aReady!
 2) §r§f§r§6Refined Titanium§r§7: §r§aReady!
 3) §r§f§r§6Refined Titanium§r§7: §r§aReady!
 4) §r§f§r§6Refined Titanium§r§7: §r§aReady!
 5) §r§f§r§6Refined Titanium§r§7: §r§aReady!

COMMISSIONS : 
§9§lCommissions:
 §r§fRaffle: §r§c0%
 §r§fGolden Goblin Slayer: §r§c0%
 §r§fTreasure Hoarder Puncher: §r§a80%
 §r§fRampart's Quarry Mithril: §r§c0%

POWDER : 
§9§lPowders:
 Mithril: §r§2292,385
 Gemstone: §r§d213,333
 Glacite: §r§b1,351,833

</details>

**Comment by Thunderblade73** [comment]
updated.

**Pull request merged**
