### PR TITLE
Feature: SBA Chroma but in SH

### PR DESCRIPTION
**Pull request by VixidDev**
Adds SBA Chroma to SkyHanni. Currently only adds 1 immediate feature; Everything Chroma, which just renders everything in chroma.

- Allows §Z for chroma text just like in SBA
- Has the 3 original settings and 1 extra to change how the chroma is rendered:
    - Size
    - Speed
    - Saturation
    - Extra: Direction
         - Can change the slant direction (Forwards / Backwards) and which direction the chroma moves (Right / Left)
- Works with SBA at the same time, although in almost all cases SBA's chroma will take priority
- Everything Chroma kinda breaks with SBA's enchant parsing with some enchants rendering as white

I'll maybe try to add enchant parsing to SkyHanni so the point above isn't an issue, and then it will obviously make use of SkyHanni's chroma since SBA is becoming more obsolete. Adding Text Replace from SBE can also then make use of this which I don't mind adding also.

Edit: Will not work in NEU's /neuec without SBA since §Z is only considered a valid color by it if SBA is loaded [see here](https://github.com/NotEnoughUpdates/NotEnoughUpdates/blob/aa6c2ef258e35fbfbade6fb26ac6732eb2856456/src/main/java/io/github/moulberry/notenoughupdates/miscfeatures/item/enchants/EnchantMatcher.java#L44). But will work with renaming items in /neucustomize since it doesn't share the same restriction

### CODE REVIEW

**Comment by NetheriteMiner** [comment]
What's the difference between this and neu's chroma?

**Comment by hannibal002** [comment]
> What's the difference between this and neu's chroma?

NEU's chroma goes like this: new color, wait, new color, wait, new color, wait
SBA's chroma goes like this: new color, new color, new color, new color, new c, new c, new c, c, ,c,c, newwwww

(It's way faster)

One is tick-based (20 times a second) the other is only updating 3–5 times a second.

There is a slight chance that I confused what is faster, but my main point stands: they both have different speeds of animation

**Comment by hannibal002** [comment]
image

**Comment by hannibal002** [comment]
Or the difference is that NEU chroma is one char one color, SBA chroma is one pixel one color with smoother animations. 
objectively said, the SBA'approach is more stylistic, but some still prefer the classic NEU animation.

**Comment by VixidDev** [comment]
> Or the difference is that NEU chroma is one char one color, SBA chroma is one pixel one color with smoother animations. 

Yep, basically this, SBA's chroma uses shaders to color each pixel, whereas NEU colors each char with Minecraft's color codes and each adjacent char is offset by a color

**Comment by Kurumi78** [comment]
No clue if intentional, but for the record I had to [add an import](https://github.com/Kurumi78/SkyHanni/commit/22d57b538be2319227be83ac43ab50885c826fda) to get this to compile

**Comment by hannibal002** [comment]
> No clue if intentional, but for the record I had to [add an import](https://github.com/Kurumi78/SkyHanni/commit/22d57b538be2319227be83ac43ab50885c826fda) to get this to compile

please dont import with wildcards:

https://user-images.githubusercontent.com/24389977/273290557-84c3a640-b39a-407e-a73c-12e548f33e88.png

**Comment by VixidDev** [comment]
> No clue if intentional, but for the record I had to [add an import](https://github.com/Kurumi78/SkyHanni/commit/22d57b538be2319227be83ac43ab50885c826fda) to get this to compile

In the Features.java, all the configs were already imported with the wildcard when I PR'd, so the ChromaConfig was already included.

> > No clue if intentional, but for the record I had to [add an import](https://github.com/Kurumi78/SkyHanni/commit/22d57b538be2319227be83ac43ab50885c826fda) to get this to compile
> 
> please dont import with wildcards:
> 
> https://user-images.githubusercontent.com/24389977/273290557-84c3a640-b39a-407e-a73c-12e548f33e88.png

Should I change it to import each rather than using the wildcard?

**Comment by hannibal002** [comment]
> Should I change it to import each rather than using the wildcard?

yes please do so. You might also want to merge beta into your branch to have the latest version as well

**Comment by Kurumi78** [comment]
> > No clue if intentional, but for the record I had to [add an import](https://github.com/Kurumi78/SkyHanni/commit/22d57b538be2319227be83ac43ab50885c826fda) to get this to compile
> 
> please dont import with wildcards:
> 
> https://user-images.githubusercontent.com/24389977/273290557-84c3a640-b39a-407e-a73c-12e548f33e88.png

Usually I try not to, I didn't know that was an option in IntelliJ and didn't plan on PRing my commit so I just didn't care enough to manually fix it. Learn something new everyday. .

**Comment by Kurumi78** [comment]
[Something has gone terribly, terribly wrong somewhere](https://youtu.be/QmAq9TRSdoA) and I dont know how to describe this. EDIT: epilepsy warning

**Comment by VixidDev** [comment]
> [Something has gone terribly, terribly wrong somewhere](https://youtu.be/QmAq9TRSdoA) and I dont know how to describe this. EDIT: epilepsy warning

Uhhh, did you change anything in the code? Also what mods were you running?

**Comment by Kurumi78** [comment]
> > [Something has gone terribly, terribly wrong somewhere](https://youtu.be/QmAq9TRSdoA) and I dont know how to describe this. EDIT: epilepsy warning
> 
> Uhhh, did you change anything in the code? Also what mods were you running?


Other than that the imports in my commit, no. I just opened it in IntelliJ, changed the imports then "gradlew assemble" for the jar. [I do have a rather beefy mod folder though.](https://i.imgur.com/3kKJ56C.png) Could be it. Ill remove everything but SkyHanni and see if its still around.

**Comment by Kurumi78** [comment]
Im going to be honest. Whatever just happened I need to look into it more. I disabled all of my mods and the bug went away, I re-enabled all of them and it didnt come back. [Everything is working perfectly with my full mod list](https://i.imgur.com/hHuie4v.png). Ill some some more messing around and see if I can come up with anything or a consistent way to reproduce it.

**Review by hannibal002 — CHANGES_REQUESTED** [review]
It does break when using patcher: the sky flickers hard and the full screen has funny color effects:
image

**Comment by hannibal002** [comment]
Any chance you can look into sba's approach to patcher support a bit further? @VixidDev

**Comment by hannibal002** [comment]
As cal found out, it is the feature "optimised font renderer" from patcher

**Comment by VixidDev** [comment]
> Any chance you can look into sba's approach to patcher support a bit further? @VixidDev

Completely forgot about this. SBA handled this from Patcher and I intended to do the same once I had got the chroma working but completely forgot, I'll get on it now

**Review by hannibal002 — APPROVED** [review]
works like a charm!

**Pull request merged**
