### PR TITLE
Improvement: Refactor of /ff for Improved Modularity and Code Reusability

### PR DESCRIPTION
**Pull request by Thunderblade73**
## Dependencies
- #822
- #821
- #885 
- #886
- #887
- #888
# What
The primary goal is to enhance modularity and code reusability. The intention is to maintain the existing user experience while significantly enhancing our ability to extend functionality. For instance, adding new items to ff or making similar features for other things like mining or fishing.

Major Changes:
- **Modular Structure:** Separates the GUI, logic, and data.
- **Dynamic GUI Implementation:** Updates the GUI implementation to use Renderables and adopted a more dynamic coding approach. Say goodbye to hardcoded pixel values!!!
- **Code Reusability:** Improves the overall reusability of the code, making it easier for us to make similar features.

## Note
it is not quiet there where I wanted it to be, but it is better than before and I want to push the changes to beta.

## Changelog Improvements
+ Minor GUI improvements in /ff. - Thunderblade73
## Changelog Technical Details
+ Refactored /ff. - Thunderblade73

### CODE REVIEW

**Comment by lunaynx** [comment]
Oh thank god, I think this will make it easier for me to add Armor Enchantment Fortune without going insane.

**Comment by Thunderblade73** [comment]
Dependencies are:
- #822
- #821
- #885 
- #886
- #887
- #888

**Comment by hannibal002** [comment]
```
SkyHanni 0.25.Beta.23: Something broke in GuideGUI
 
Caused by java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at SH.utils.renderables.Renderable$Companion$scrollTable$1.render(Renderable.kt:780)
	at SH.utils.guide.GuideRenderablePage.drawPage(GuideRenderablePage.kt:15)
	at SH.utils.guide.GuideGUI$drawScreen$1.invoke(GuideGUI.kt:105)
	at SH.utils.guide.GuideGUI$drawScreen$1.invoke(GuideGUI.kt:94)
	at SH.utils.renderables.Renderable$Companion.withMousePosition(Renderable.kt:65)
	at SH.utils.guide.GuideGUI.drawScreen(GuideGUI.kt:94)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
	at MC.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1104)
	at MC.client.Minecraft.runGameLoop(Minecraft.java:1051)
	at MC.client.Minecraft.run(Minecraft.java:349)
	at MC.client.main.Main.main(Main.java:124)

Extra data:
Guide: 'at.hannibal2.skyhanni.features.garden.fortuneguide.FFGuideGUI'
Page: 'UPGRADES'
```

**Review by CalMWolfs — CHANGES_REQUESTED** [review]
From a read through the code, it all looks pretty good, but a few issues I've found while testing

This seems to be missing colour, also im guessing the clicking to toggle the stat is gone, thats a shame but you dont need to bring back that behaviour.

image

Also maybe im doing somethign wrong but most pages are missing tool info
Only a few of the pages have the tool data

image

The other pages just dont
image

**Review by CalMWolfs — APPROVED** [review]
changes worked

**Review by hannibal002 — APPROVED** [review]
Looks fine to me. I need gemstone support now

**Pull request merged**
