### PR TITLE
Fix: Heat "null" on Custom Scoreboard

### PR DESCRIPTION
**Pull request by DavidArthurCole**
## What
https://discord.com/channels/997079228510117908/1322382921755005009
Fixes heat being null when 0

## Changelog Fixes
+ Fixed heat showing as `null` in Custom Scoreboard. - Daveed

### CODE REVIEW

**Comment by j10a1n15** [comment]
I feel like this will fuck this part up 

https://github.com/hannibal002/SkyHanni/blob/beta/src/main/java/at/hannibal2/skyhanni/features/gui/customscoreboard/ChunkedStatsLine.kt (I can't copy lines on mobile, should be at ~70 or smth (where heat is))

**Comment by j10a1n15** [comment]
It would probably be best to add a y check similar to this

https://github.com/j10a1n15/CustomScoreboard/blob/main/src/main/kotlin/gay/j10a1n15/customscoreboard/feature/customscoreboard/elements/ElementHeat.kt

**Comment by j10a1n15** [comment]
Crazy how my concern wasn't implemented yet this was still merged

**Comment by hannibal002** [comment]
ive missed your comments, im sorry!

anyway, I dont see the problem the pr should cause here, we still compare the same value
image
image

**Comment by hannibal002** [comment]
wait do we want to use null and and intentionally hide it when not found?

**Comment by j10a1n15** [comment]
Yes

**Pull request merged**
