### PR TITLE
Add shtestmessage for complex messages

### PR DESCRIPTION
**Pull request by lineargraph**
## What
Allows to use `/shtestmessage -complex` to test components in json format (like the ones you get from shift-clicking `/shchathistory`)

<details>
<summary>Images</summary>

image

</details>

## Changelog Technical Details
+ Allows use of `/shtestmessage -complex` to test components in JSON format. - nea
    * Similar to those obtained from shift-clicking `/shchathistory`.

### CODE REVIEW

**Review by hannibal002 — CHANGES_REQUESTED** [review]
`/shtestmessage -clipboard -complex` works fine, cool!
image

two problems:

`/shtestmessage -complex` throws an error.

also, those errors aren't shown in chat via ErrorManager. `SkyHanniMod.coroutineScope.launch {` is eating them, this is bad

**Comment by hannibal002** [comment]
Also please change the changelog from improvement to backend/internal change

**Comment by hannibal002** [comment]
also maybe this
image

**Comment by lineargraph** [comment]
> /shtestmessage -complex throws an error.

-complex on its own does not imply -clipboard.

**Comment by hannibal002** [comment]
> -complex on its own does not imply -clipboard.

i know. still, using the command wrongly should not throw an error.

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
