### PR TITLE
Fix: New Rift CS Lines

### PR DESCRIPTION
**Pull request by j10a1n15**
## What
Added some new lines, probably not all though since I didnt play yet

## Changelog Fixes
+ Fixed Custom Scoreboard errors from Rift update. - j10a1n15

### CODE REVIEW

**Review by hannibal002 — CHANGES_REQUESTED** [review]
this will just hide the "unknown lines" information.
in this context, i dont think this is productive. instead. the user wants to see if their time is sliced or the time until the big damage is coming in.
instead of this, add a option to include those settings. I know this is more complex than simply hiding the error messages, but we dont want to "just hide" them.

remember, the default settings of the custom scoreboard should not hide information the vanilla scoreboard provides.

**Comment by j10a1n15** [comment]
What?
This pr adds the new lines to the rift lines? The rift option is default enabled on the events priority list. I don't see how this hides information

**Review by hannibal002 — APPROVED** [review]
Sorry!

this list keeps confusing me. we should remove the list in the future and instead iterate over all known pattern objects to build the "known pattern list" dynamically
image

**Comment by j10a1n15** [comment]
> this list keeps confusing me. we should remove the list in the future and instead iterate over all known pattern objects to build the "known pattern list" dynamically

> 

This is alr an Open pr https://github.com/hannibal002/SkyHanni/pull/2927

**Pull request merged**
