### PR TITLE
Feature: click on playtime item to copy

### PR DESCRIPTION
**Pull request by catgirlseraid**
## What
Click on playtime overview item in /playtimedetailed to copy hours
useful for users of https://discord.com/channels/997079228510117908/1196872092579274872

image

catgirlseraid's Playtime Stats
41.3 hours on Hub
13.1 hours on Private Island
2.6 hours on Gold Mine
2.5 hours on Dungeon Hub
34 minutes on Deep Caverns
16 minutes on Garden
8 minutes on The Rift
4 minutes on The Park
2 minutes on Spider's Den
1 minute on Jerry's Workshop
Totalling 60.5 hours on this profile!

## Changelog New Features
+ Click on breakdown display in /playtimedetailed to copy the stats into the clipboard. - seraid

### CODE REVIEW

**Comment by Thunderblade73** [comment]
It didn't copy limbo time, since this is added from SkyHanni. But not copying it would confuse some people.

**Comment by catgirlseraid** [comment]
> It didn't copy limbo time, since this is added from SkyHanni. But not copying it would confuse some people.

thanks, fixed <3

**Comment by ItsEmpa** [comment]
could also specify in the first line what profile its in? like
catgirlseraid's Playtime Stats on Pomegranate
or similar

**Comment by catgirlseraid** [comment]
> could also specify in the first line what profile its in? like catgirlseraid's Playtime Stats on Pomegranate or similar

done <3

**Review by CalMWolfs — APPROVED** [review]

**Pull request merged**
