### PR TITLE
Improvement: Hoppity eggs timer outside sb

### PR DESCRIPTION
**Pull request by maxime-bodifee**
## What
Add config option to toggle egg timer outside of Skyblock

<details>
<summary>Images</summary>

</details>

## Changelog Improvements
+ Option to show Hoppity Eggs timer outside of SkyBlock. - maxime-bodifee

### CODE REVIEW

**Comment by maxime-bodifee** [comment]
@hannibal002 does the Version 0.26 milestone mean it'll get released with the next beta?

**Comment by RayDeeUx** [comment]
> @hannibal002 does the Version 0.26 milestone mean it'll get released with the next beta?

@maxime-bodifee not quite, more accurately the next 0.xx version of skyhanni

**Comment by maxime-bodifee** [comment]
> > @hannibal002 does the Version 0.26 milestone mean it'll get released with the next beta?
> 
> @maxime-bodifee not quite, more accurately the next 0.xx version of skyhanni

@RayDeeUx sorry I meant it just like objectively: will it be released with the next beta? or at least how I could determine that

**Comment by hannibal002** [comment]
The 0.26 milestone means that this pr is planned to get merged before 0.26 full version gets released. So it will be part of any beta before that. This should be around couple of weeks.

**Comment by hannibal002** [comment]
The "soon" tag means this pr is planned to get merged in the next couple of betas.

Since we currently are at 70+ prs marked as 0.26 and we can't look at all prs at the same time, we hereby mark some prs as "the prs we want to look at next" so you know this pr is planned to get merged soon, compared to all the other prs with just an 0.26 milestone. 

Ideally we get 10+ prs merged each beta, with 3-5 betas a week.

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
