### PR TITLE
new Gemstone Slot Unlock Cost line for Estimated Item Value feature

### PR DESCRIPTION
**Pull request by Fix3dll**
Depends on https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/pull/954

### CODE REVIEW

**Comment by NetheriteMiner** [comment]
FYI, you can use [draft pull requests](https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests) instead of putting [WIP] in the title

**Comment by Fix3dll** [comment]
ss1

**Comment by Fix3dll** [comment]
image

**Comment by jani270** [comment]
Hannibal converted this to a draft, as I think it's a better idea to wait for the next neu alpha, which will bundle the newest version of the repo (including the gemstone cost json). Merging this now could create problems with users who are using the bundled/backup of the repo.

**Comment by Fix3dll** [comment]
@jani270 @hannibal002 NEU-REPO PR merged now. NEU Alpha 20.1 contains `gemstonecosts.json`

**Comment by hannibal002** [comment]
@Fix3dll for the future, please create a copy of your beta branch for PRs

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
