### PR TITLE
Feature: Apec Bar

### PR DESCRIPTION
**Pull request by j10a1n15**
## What
Hi guys I added the apec bar
[#1944 Editable Xp Bar](https://github.com/hannibal002/SkyHanni/pull/1944) should probably be merged before/in the same beta as this.

<details>
<summary>Images</summary>

image
image

</details>

## Changelog New Features
+ Add Apec Bar. - j10a1n15

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
surely the feature could have a name better than "bar"

**Comment by j10a1n15** [comment]
> surely the feature could have a name better than "bar"

image
yeah uhh

**Review by hannibal002 — CHANGES_REQUESTED** [review]
rename bar

**Comment by j10a1n15** [comment]
awesome name

**Comment by jani270** [comment]
Is there a reason to just steal this feature? afaik apec isnt discontinued?

**Comment by hannibal002** [comment]
Afaik apec for 1.8.9 Is dead. Last time I've seen an announcement on their discord , they were discussing a different dev porting the mod to 1.20+, but no further support for 1.8.9.

**Comment by jani270** [comment]
Well there is not much to do?

Dont see why you would steal this.

**Comment by j10a1n15** [comment]
image

**Pull request closed without merging**
