### PR TITLE
Improvement: Persistent HoppityCollectionStats display

### PR DESCRIPTION
**Pull request by appable0**
## Dependencies
- ~~https://github.com/hannibal002/SkyHanni-REPO/pull/196~~

## What
Stores rabbit counts in ProfileSpecificStorage so that users no longer have to open all pages of the Hoppity Collection menu on each restart. Also updates rabbit counts on chat messages. 

## Changelog Improvements
+ Hoppity Collection Stats are now persistent. - appable
    * No longer reset on profile swap or game restart.

### CODE REVIEW

**Comment by appable0** [comment]
~~Temporarily draft status to switch to NEU repo instead of duplicating in SH, per the discussion in the repo PR.~~

EDIT: now uses NEU repo, no longer dependent on SH repo PR.

**Comment by CalMWolfs** [comment]
Will look at this after the changes on the alpha server are on main

**Comment by appable0** [comment]
Changes:
- Moved some of the NEU repo logic to a new file
  - No longer stores rabbits that have not yet been found (should save a bit of storage)
  - Only will store rabbits known in the NEU repo
  - Total rabbits and total rabbits by rarity taken from NEU repo
- Added a user bugfix command to clear saved rabbits
  - There's no other way to reset if you get rabbits on alpha and then go back to main, which desyncs everything. 

~~Works on alpha, but a couple other PRs needed first:~~
~~- https://github.com/hannibal002/SkyHanni/pull/1860/ (for divine rarity)~~
~~- https://github.com/hannibal002/SkyHanni/pull/1874 (for detecting rabbits where requirement is not met and therefore they cannot be found)~~

**Comment by appable0** [comment]
This is working on main server without dependent PRs now.

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
