### PR TITLE
Improvement: Multiple chat clicks

### PR DESCRIPTION
**Pull request by hannibal002**
## What
made normal clickable chat message multiple times clickable, and disable this for some cases

## Changelog Improvements
+ Allow multiple clicks on the same SkyHanni chat message. - hannibal2

### CODE REVIEW

**Comment by ThatGravyBoat** [comment]
I improved how these click events work in #1718 in terms of performance and usability, should I include this change in there by changing the default and changing the few that need oneTimeClick and then that can supersede this instead of getting merge conflicts for it to be instantly changed again?

**Comment by hannibal002** [comment]
yes, good catch. Should i keep the "set to only one time" changes in this pr or do you wanna merge it entirely into your pr?

**Comment by ThatGravyBoat** [comment]
> yes, good catch. Should i keep the "set to only one time" changes in this pr or do you wanna merge it entirely into your pr?

Ive merged it into my PR

**Comment by hannibal002** [comment]
yield for https://github.com/hannibal002/SkyHanni/pull/1718

**Pull request closed without merging**
